// src/components/ReportForm.tsx
import React, {
  useState,
  useEffect,
  forwardRef,
  useImperativeHandle,
} from "react";
import {
  StyleSheet,
  View,
  Text,
  Platform,
  Alert,
  TouchableOpacity,
} from "react-native";
import { TextInput, Button, HelperText, useTheme } from "react-native-paper";
import { useForm, Controller } from "react-hook-form";
import { DownloadDialog } from "./DownloadDialog";
import { reportService, ReportFormValues } from "../services/ReportService";
import { checkIsJsonService } from "../services/CheckIsJsonService";
import { storageService } from "../services/StorageService";
import { fileService } from "../services/FileService";

interface ReportFormProps {
  loading: (state: boolean) => void;
  scanValue: string;
  cancel: boolean;
  qrScanValue: (val: string) => void;
  onNotification?: (
    type: "success" | "error",
    title: string,
    message: string,
  ) => void;
}

export interface ReportFormHandle {
  openReport: () => void;
}

const ReportForm = forwardRef<ReportFormHandle, ReportFormProps>(
  ({ loading, scanValue, cancel, onNotification }, ref) => {
    const theme = useTheme();
    const [isPasswordShow, setIsPasswordShow] = useState(false);
    const [downloadProgress, setDownloadProgress] = useState<number | null>(
      null,
    );
    const [dialogVisible, setDialogVisible] = useState(false);
    const [pdfUrl, setPdfUrl] = useState<string | null>(null);
    const [localFilePath, setLocalFilePath] = useState<string | null>(null);

    const {
      control,
      handleSubmit,
      setValue,
      watch,
      formState: { errors, isValid },
    } = useForm<ReportFormValues>({
      mode: "onChange",
      defaultValues: {
        AccesionNumber: "",
        Key: "",
      },
    });

    // Load persisted accession number on mount
    useEffect(() => {
      async function loadSaved() {
        const saved = await storageService.getAccessionNumber();
        if (saved) {
          setValue("AccesionNumber", saved, { shouldValidate: true });
        }
      }
      loadSaved();
    }, [setValue]);

    // Handle cancel from parent
    useEffect(() => {
      if (cancel) {
        hideDialog();
      }
    }, [cancel]);

    // Parse scanned QR value
    useEffect(() => {
      if (!scanValue) return;

      if (checkIsJsonService.isJson(scanValue)) {
        try {
          const parsed =
            typeof scanValue === "string" ? JSON.parse(scanValue) : scanValue;
          const acc = parsed.AccesionNumber || parsed.accessionNumber || "";
          const key = parsed.Key || parsed.key || "";
          if (acc) setValue("AccesionNumber", acc, { shouldValidate: true });
          if (key) setValue("Key", key, { shouldValidate: true });
        } catch {
          setValue("Key", scanValue, { shouldValidate: true });
        }
      } else {
        setValue("Key", scanValue, { shouldValidate: true });
      }
    }, [scanValue, setValue]);

    // Save accession number when changed
    useEffect(() => {
      const subscription = watch((value) => {
        if (value.AccesionNumber) {
          storageService.saveAccessionNumber(value.AccesionNumber);
        }
      });
      return () => subscription.unsubscribe();
    }, [watch]);

    const hideDialog = () => {
      fileService.cancelDownload();
      setDialogVisible(false);
      setDownloadProgress(null);
    };

    const openReport = async () => {
      const target = localFilePath || pdfUrl;
      if (target) {
        try {
          await fileService.openReport(target);
        } catch (err: any) {
          Alert.alert(
            "Error",
            "Could not open document: " + (err?.message || ""),
          );
        }
      }
      hideDialog();
    };

    useImperativeHandle(ref, () => ({
      openReport,
    }));

    const onSubmit = async (data: ReportFormValues) => {
      loading(true);
      try {
        const url = await reportService.getReportUrl(data);
        setPdfUrl(url);
        if (onNotification) {
          onNotification(
            "success",
            "Report Found",
            "Patient report URL retrieved successfully.",
          );
        }
      } catch (err: any) {
        const message = err?.message || "Error getting report";
        if (onNotification) {
          onNotification("error", "Error getting report", message);
        } else {
          Alert.alert("Error getting report", message);
        }
      } finally {
        loading(false);
      }
    };

    const handleDownload = async () => {
      if (!pdfUrl) return;

      setDownloadProgress(0);
      setDialogVisible(true);

      try {
        const savedPath = await fileService.downloadReport(
          pdfUrl,
          (progress) => {
            setDownloadProgress(progress);
          },
        );
        setLocalFilePath(savedPath);
        setDownloadProgress(100);
      } catch (err: any) {
        hideDialog();
        const msg = err?.message || "Failed to download report.";
        if (onNotification) {
          onNotification("error", "Download Error", msg);
        } else {
          Alert.alert("Download Error", msg);
        }
      }
    };

    return (
      <View style={styles.container}>
        {/* Accession Number Input */}
        <View style={styles.inputContainer}>
          <Controller
            control={control}
            name="AccesionNumber"
            rules={{ required: "Accession number is required!" }}
            render={({ field: { onChange, onBlur, value } }) => (
              <TextInput
                mode="outlined"
                label="Accession number"
                textColor={theme.colors.onSurface}
                activeOutlineColor={theme.colors.primary}
                outlineColor={
                  errors.AccesionNumber
                    ? theme.colors.error
                    : theme.colors.outline
                }
                onBlur={onBlur}
                onChangeText={onChange}
                value={value}
                style={[
                  styles.input,
                  { backgroundColor: theme.colors.surfaceVariant },
                ]}
              />
            )}
          />
          {errors.AccesionNumber && (
            <HelperText type="error" visible={true} style={styles.errorText}>
              {errors.AccesionNumber.message}
            </HelperText>
          )}
        </View>

        {/* Report Key Input */}
        <View style={styles.inputContainer}>
          <Controller
            control={control}
            name="Key"
            rules={{ required: "Report key is required!" }}
            render={({ field: { onChange, onBlur, value } }) => (
              <TextInput
                mode="outlined"
                label="Report key"
                textColor={theme.colors.onSurface}
                activeOutlineColor={theme.colors.primary}
                outlineColor={
                  errors.Key ? theme.colors.error : theme.colors.outline
                }
                secureTextEntry={!isPasswordShow}
                onBlur={onBlur}
                onChangeText={onChange}
                value={value}
                style={[
                  styles.input,
                  { backgroundColor: theme.colors.surfaceVariant },
                ]}
                right={
                  <TextInput.Icon
                    icon={isPasswordShow ? "eye-off" : "eye"}
                    color={theme.colors.onSurfaceVariant}
                    onPress={() => setIsPasswordShow(!isPasswordShow)}
                  />
                }
              />
            )}
          />
          {errors.Key && (
            <HelperText type="error" visible={true} style={styles.errorText}>
              {errors.Key.message}
            </HelperText>
          )}
        </View>

        {/* Buttons */}
        <View style={styles.buttonsContainer}>
          <Button
            mode="contained"
            buttonColor={theme.colors.primary}
            textColor={theme.colors.onPrimary}
            disabled={!isValid}
            onPress={handleSubmit(onSubmit)}
            style={styles.button}
            contentStyle={styles.buttonContent}
          >
            Search
          </Button>

          <Button
            mode="contained"
            buttonColor={theme.colors.secondary}
            textColor={theme.colors.onSecondary}
            disabled={!pdfUrl || !isValid}
            onPress={handleDownload}
            style={styles.button}
            contentStyle={styles.buttonContent}
          >
            Download
          </Button>
        </View>

        {/* Status banner when report found */}
        {pdfUrl && (
          <View
            style={[
              styles.readyBanner,
              {
                backgroundColor: theme.dark ? "#0c4a6e" : "#eff6ff",
                borderColor: theme.dark ? "#0284c7" : "#bfdbfe",
              },
            ]}
          >
            <Text
              style={[
                styles.readyTitle,
                { color: theme.dark ? "#bae6fd" : "#1e40af" },
              ]}
            >
              Report ready for download!
            </Text>
          </View>
        )}

        {/* Download Dialog */}
        <DownloadDialog
          show={dialogVisible}
          cancel={hideDialog}
          open={openReport}
          downloadProgress={downloadProgress}
          title={
            downloadProgress !== null && downloadProgress >= 100
              ? "Successfully downloaded!"
              : "Downloading report..."
          }
          reportUrl={pdfUrl}
        />
      </View>
    );
  },
);

const styles = StyleSheet.create({
  container: {
    width: "100%",
    paddingVertical: 8,
  },
  inputContainer: {
    marginBottom: 10,
  },
  input: {
    backgroundColor: "#ffffff",
    fontSize: 15,
  },
  errorText: {
    paddingHorizontal: 4,
    color: "#dc2626",
  },
  buttonsContainer: {
    marginTop: 8,
    gap: 12,
  },
  button: {
    borderRadius: 12,
    marginVertical: 4,
  },
  buttonContent: {
    paddingVertical: 6,
  },
  readyBanner: {
    marginTop: 14,
    padding: 12,
    backgroundColor: "#eff6ff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  readyTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1e40af",
  },
  readyUrl: {
    fontSize: 11,
    color: "#64748b",
    marginTop: 2,
  },
});

export default ReportForm;

// src/app/components/report-form.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  inject,
  signal
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { View, Text, TextInput, Pressable } from '@ng-native/components';
import { ReportService } from '../services/report.service';
import { StorageService } from '../services/storage.service';
import { FileService } from '../services/file.service';
import { DownloadDialogComponent } from './download-dialog.component';
import { NotificationState, ReportFormValues } from '../models/report.model';

@Component({
  selector: 'app-report-form',
  standalone: true,
  imports: [CommonModule, View, Text, TextInput, Pressable, DownloadDialogComponent],
  template: `
    <view class="form-wrapper">
      <!-- Accession Number Field -->
      <view class="field-group">
        <text class="field-label">Accession Number</text>
        <text-input
          [value]="accessionNumber()"
          (changeText)="onAccessionChange($event)"
          placeholder="e.g. ACC-2024-987"
          class="input-box"
        />
        <text *ngIf="showAccessionError()" class="error-msg">
          Accession number is required!
        </text>
      </view>

      <!-- Report Key Field with show/hide password toggle -->
      <view class="field-group">
        <text class="field-label">Report Key</text>
        <view class="password-row">
          <text-input
            [value]="reportKey()"
            (changeText)="onKeyChange($event)"
            [secureTextEntry]="!isPasswordShow()"
            placeholder="Enter your security key"
            class="input-box password-input"
          />
          <pressable class="toggle-eye" (press)="togglePasswordShow()">
            <text class="toggle-eye-icon">{{ isPasswordShow() ? '🔒' : '👁️' }}</text>
          </pressable>
        </view>
        <text *ngIf="showKeyError()" class="error-msg">
          Report key is required!
        </text>
      </view>

      <!-- Action buttons -->
      <view class="buttons-stack">
        <pressable
          class="btn-primary"
          [class.btn-disabled]="!canSearch()"
          (press)="onSearch()"
        >
          <text class="btn-primary-text">Search</text>
        </pressable>

        <pressable
          class="btn-secondary"
          [class.btn-disabled]="!canDownload()"
          (press)="onDownload()"
        >
          <text class="btn-secondary-text">Download</text>
        </pressable>
      </view>

      <!-- Ready banner when report found -->
      <view *ngIf="pdfUrl()" class="ready-banner">
        <text class="ready-title">✓ Report ready for download!</text>
        <text class="ready-subtitle">Accession match verified.</text>
      </view>

      <!-- Download progress modal -->
      <app-download-dialog
        [show]="dialogVisible()"
        [downloadProgress]="downloadProgress()"
        [title]="downloadProgress() !== null && downloadProgress()! >= 100 ? 'Successfully downloaded!' : 'Downloading report...'"
        (cancelled)="onHideDialog()"
        (opened)="onOpenReport()"
      />
    </view>
  `,
  styles: `
    .form-wrapper {
      width: 100%;
      gap: 16px;
    }
    .field-group {
      gap: 6px;
    }
    .field-label {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #64748b;
    }
    .input-box {
      width: 100%;
      padding: 12px 14px;
      font-size: 14px;
      border-radius: 12px;
      background-color: #f8fafc;
      border: 1px solid #cbd5e1;
      color: #0f172a;
    }
    .password-row {
      position: relative;
      flex-direction: row;
      align-items: center;
    }
    .password-input {
      padding-right: 48px;
    }
    .toggle-eye {
      position: absolute;
      right: 10px;
      padding: 8px;
      justify-content: center;
      align-items: center;
    }
    .toggle-eye-icon {
      font-size: 16px;
    }
    .error-msg {
      font-size: 11px;
      color: #ef4444;
      margin-top: 2px;
      padding-left: 4px;
    }
    .buttons-stack {
      gap: 10px;
      margin-top: 6px;
    }
    .btn-primary {
      width: 100%;
      padding: 14px;
      background-color: #002E62;
      border-radius: 14px;
      align-items: center;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    .btn-primary-text {
      color: #ffffff;
      font-size: 15px;
      font-weight: 700;
    }
    .btn-secondary {
      width: 100%;
      padding: 14px;
      background-color: #0284c7;
      border-radius: 14px;
      align-items: center;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    .btn-secondary-text {
      color: #ffffff;
      font-size: 15px;
      font-weight: 700;
    }
    .btn-disabled {
      opacity: 0.5;
    }
    .ready-banner {
      padding: 14px;
      background-color: #eff6ff;
      border: 1px solid #bfdbfe;
      border-radius: 12px;
      gap: 2px;
    }
    .ready-title {
      font-size: 13px;
      font-weight: 700;
      color: #1e40af;
    }
    .ready-subtitle {
      font-size: 11px;
      color: #3b82f6;
    }
    @media (prefers-color-scheme: dark) {
      .field-label {
        color: #94a3b8;
      }
      .input-box {
        background-color: #0f172a;
        border-color: #334155;
        color: #f8fafc;
      }
      .btn-primary {
        background-color: #0284c7;
      }
      .ready-banner {
        background-color: rgba(2, 132, 199, 0.15);
        border-color: #0284c7;
      }
      .ready-title {
        color: #38bdf8;
      }
      .ready-subtitle {
        color: #7dd3fc;
      }
    }
  `
})
export class ReportFormComponent implements OnInit {
  @Input() set scanValue(val: string) {
    if (!val) return;
    this.parseScanValue(val);
  }

  @Output() loadingState = new EventEmitter<boolean>();
  @Output() notify = new EventEmitter<NotificationState>();

  accessionNumber = signal('');
  reportKey = signal('');
  isPasswordShow = signal(false);
  pdfUrl = signal<string | null>(null);
  downloadProgress = signal<number | null>(null);
  dialogVisible = signal(false);

  showAccessionError = signal(false);
  showKeyError = signal(false);

  private reportService = inject(ReportService);
  private storageService = inject(StorageService);
  private fileService = inject(FileService);

  constructor() {}

  ngOnInit(): void {
    const saved = this.storageService.getAccessionNumber();
    if (saved) {
      this.accessionNumber.set(saved);
    }
  }

  onAccessionChange(val: string): void {
    this.accessionNumber.set(val);
    this.storageService.saveAccessionNumber(val);
    if (val.trim()) {
      this.showAccessionError.set(false);
    }
  }

  onKeyChange(val: string): void {
    this.reportKey.set(val);
    if (val.trim()) {
      this.showKeyError.set(false);
    }
  }

  togglePasswordShow(): void {
    this.isPasswordShow.set(!this.isPasswordShow());
  }

  canSearch(): boolean {
    return !!(this.accessionNumber().trim() && this.reportKey().trim());
  }

  canDownload(): boolean {
    return !!(this.pdfUrl() && this.canSearch());
  }

  parseScanValue(raw: string): void {
    try {
      const parsed = JSON.parse(raw);
      const acc = parsed.AccesionNumber || parsed.accessionNumber || '';
      const key = parsed.Key || parsed.key || '';
      if (acc) this.accessionNumber.set(acc);
      if (key) this.reportKey.set(key);
    } catch {
      this.reportKey.set(raw);
    }
  }

  async onSearch(): Promise<void> {
    if (!this.accessionNumber().trim()) {
      this.showAccessionError.set(true);
      return;
    }
    if (!this.reportKey().trim()) {
      this.showKeyError.set(true);
      return;
    }

    this.loadingState.emit(true);
    try {
      const values: ReportFormValues = {
        AccesionNumber: this.accessionNumber().trim(),
        Key: this.reportKey().trim(),
      };
      const url = await this.reportService.getReportUrl(values);
      this.pdfUrl.set(url);
      this.notify.emit({
        type: 'success',
        title: 'Report Found',
        message: 'Patient report URL retrieved successfully.',
      });
    } catch (err: any) {
      this.notify.emit({
        type: 'error',
        title: 'Error getting report',
        message: err?.message || 'Unable to retrieve report with provided parameters.',
      });
    } finally {
      this.loadingState.emit(false);
    }
  }

  async onDownload(): Promise<void> {
    const url = this.pdfUrl();
    if (!url) return;

    this.downloadProgress.set(0);
    this.dialogVisible.set(true);

    try {
      await this.fileService.downloadReport(url, (pct) => {
        this.downloadProgress.set(pct);
      });
      this.downloadProgress.set(100);
    } catch (err: any) {
      this.onHideDialog();
      this.notify.emit({
        type: 'error',
        title: 'Download Error',
        message: err?.message || 'Failed to download report document.',
      });
    }
  }

  onHideDialog(): void {
    this.fileService.cancelDownload();
    this.dialogVisible.set(false);
    this.downloadProgress.set(null);
  }

  onOpenReport(): void {
    const url = this.pdfUrl();
    if (url) {
      this.fileService.openReport(url);
    }
    this.onHideDialog();
  }
}
