// src/App.tsx
import React, { useState, useRef } from 'react';
import { QrCode, RefreshCw, CheckCircle2, AlertCircle, X, ShieldCheck } from 'lucide-react';
import { QrCodeScan } from './components/QrCodeScan';
import ReportForm, { ReportFormHandle } from './components/ReportForm';
import logoImg from './assets/images/logo-mini.png';

interface NotificationState {
  type: 'success' | 'error';
  title: string;
  message: string;
}

export const App: React.FC = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [qrScan, setQrScan] = useState<boolean>(false);
  const [qrScanValue, setQrScanValue] = useState<string>('');
  const [isCancel, setIsCancel] = useState<boolean>(false);
  const [notification, setNotification] = useState<NotificationState | null>(null);

  const reportFormRef = useRef<ReportFormHandle | null>(null);

  const showNotification = (type: 'success' | 'error', title: string, message: string) => {
    setNotification({ type, title, message });
    setTimeout(() => {
      setNotification((curr) => (curr?.title === title ? null : curr));
    }, 6000);
  };

  return (
    <div id="app-root" className="min-h-screen bg-slate-50 flex flex-col justify-between">
      {!qrScan ? (
        <div className="w-full flex-1 flex flex-col items-center justify-center p-4 sm:p-6 md:p-8">
          {/* Main Card */}
          <main
            id="main-content-card"
            className="w-full max-w-md bg-white rounded-3xl shadow-xl border border-slate-100 overflow-hidden relative"
          >
            {/* Top Bar with QR scan button */}
            <div className="flex justify-end p-4 pb-0">
              <button
                id="open-qr-scan-btn"
                type="button"
                onClick={() => setQrScan(true)}
                title="Scan QR Code"
                className="flex items-center gap-1.5 px-3 py-2 bg-slate-50 hover:bg-slate-100 text-[#002E62] rounded-xl border border-slate-200 transition active:scale-95 text-xs font-semibold"
              >
                <QrCode className="w-4 h-4 text-[#3C8DBC]" />
                <span>Scan QR</span>
              </button>
            </div>

            {/* Header / Brand info */}
            <header className="px-6 pt-2 pb-6 text-center">
              <div className="inline-flex items-center justify-center p-3 bg-slate-50 rounded-2xl mb-3 shadow-xs border border-slate-100">
                <img
                  src={logoImg}
                  alt="PGx Reports Logo"
                  className="w-16 h-16 object-contain"
                />
              </div>

              <h1 id="app-title" className="text-2xl sm:text-3xl font-bold text-[#002E62] tracking-tight">
                PGx Reports
              </h1>
              <p id="app-subtitle" className="mt-2 text-xs sm:text-sm text-slate-500 max-w-xs mx-auto leading-relaxed">
                Enter or scan your report key to download and view your pharmacogenomics report
              </p>
            </header>

            {/* Form Section */}
            <section className="px-6 pb-8">
              <ReportForm
                ref={reportFormRef}
                loading={setLoading}
                scanValue={qrScanValue}
                cancel={isCancel}
                qrScanValue={setQrScanValue}
                onNotification={showNotification}
              />
            </section>
          </main>

          {/* Security & Verification Footer */}
          <footer className="mt-6 flex items-center justify-center gap-1.5 text-xs text-slate-400">
            <ShieldCheck className="w-4 h-4 text-slate-400" />
            <span>Secure Diagnostic Patient Portal</span>
          </footer>
        </div>
      ) : (
        <QrCodeScan
          onClear={() => setQrScan(false)}
          qrScanValue={(val) => {
            setQrScanValue(val);
            setQrScan(false);
            showNotification('success', 'QR Code Scanned', 'Report parameters loaded.');
          }}
        />
      )}

      {/* Global Loading Spinner */}
      {loading && (
        <div
          id="global-loading-overlay"
          className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-black/60 backdrop-blur-xs text-white"
        >
          <div className="bg-slate-900/90 p-6 rounded-2xl flex flex-col items-center gap-3 border border-slate-800 shadow-2xl">
            <RefreshCw className="w-8 h-8 text-[#3C8DBC] animate-spin" />
            <p className="text-sm font-medium text-slate-200">Retrieving PGx Report...</p>
          </div>
        </div>
      )}

      {/* Global Toast Notification */}
      {notification && (
        <div
          id="app-toast"
          className="fixed bottom-6 right-6 left-6 sm:left-auto sm:max-w-sm z-50 flex items-start gap-3 p-4 bg-white rounded-2xl shadow-2xl border border-slate-200 animate-slideUp"
        >
          {notification.type === 'success' ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
          ) : (
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
          )}
          <div className="flex-1 text-xs">
            <h4 className="font-semibold text-slate-900">{notification.title}</h4>
            <p className="text-slate-600 mt-0.5">{notification.message}</p>
          </div>
          <button
            id="close-toast-btn"
            type="button"
            onClick={() => setNotification(null)}
            className="p-1 text-slate-400 hover:text-slate-600 rounded-lg"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      )}
    </div>
  );
};

export default App;

// src/app/app.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { View, Text, Pressable, ScrollView, Image } from '@ng-native/components';
import { StorageService } from './services/storage.service';
import { ReportFormComponent } from './components/report-form.component';
import { QrScannerComponent } from './components/qr-scanner.component';
import { NotificationState } from './models/report.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ScrollView, View, Text, Pressable, Image, ReportFormComponent, QrScannerComponent],
  template: `
    <view class="screen-root" [class.dark-theme]="isDark()">
      <!-- Scrollable Main Content -->
      <scroll-view class="scroll-container">
        <view class="content-wrapper">
          <view class="app-card">
            <!-- Top Bar with Theme and QR buttons -->
            <view class="top-bar">
              <pressable class="action-btn" (press)="toggleTheme()">
                <text class="action-btn-icon">{{ isDark() ? '☀️' : '🌙' }}</text>
              </pressable>

              <pressable class="action-btn" (press)="isScanning.set(true)">
                <text class="action-btn-icon">📷</text>
              </pressable>
            </view>

            <!-- Header Branding -->
            <view class="header-section">
              <view class="logo-wrapper">
                <image source="/src/assets/images/logo-mini.png" class="logo-img" />
              </view>
              <text class="app-title">PGx Reports</text>
              <text class="app-subtitle">
                Enter or scan your report key to download your PGx report
              </text>
            </view>

            <!-- Form Component -->
            <app-report-form
              [scanValue]="scannedValue()"
              (loadingState)="isLoading.set($event)"
              (notify)="showNotification($event)"
            />
          </view>
        </view>
      </scroll-view>

      <!-- Live QR Scanner View -->
      <app-qr-scanner
        *ngIf="isScanning()"
        (qrDetected)="onQrScanned($event)"
        (closeScanner)="isScanning.set(false)"
      />

      <!-- Global Loading Overlay -->
      <view *ngIf="isLoading()" class="loading-overlay">
        <view class="loading-card">
          <text class="loading-text">Loading PGx Report...</text>
        </view>
      </view>

      <!-- Toast / Notification Banner -->
      <view *ngIf="notification()" class="toast-banner" [class.toast-error]="notification()?.type === 'error'">
        <view class="toast-content">
          <text class="toast-title">{{ notification()?.title }}</text>
          <text class="toast-message">{{ notification()?.message }}</text>
        </view>
        <pressable class="toast-close" (press)="notification.set(null)">
          <text class="toast-close-text">✕</text>
        </pressable>
      </view>
    </view>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      flex: 1 1 auto;
      width: 100%;
      min-height: 100vh;
    }
    .screen-root {
      display: flex;
      flex-direction: column;
      flex: 1 1 auto;
      width: 100%;
      min-height: 100vh;
      background-color: #f8fafc;
    }
    .dark-theme {
      background-color: #0b1329;
    }
    .scroll-container {
      display: flex;
      flex-direction: column;
      flex: 1 1 auto;
      width: 100%;
      min-height: 100vh;
    }
    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 100%;
      min-height: 100vh;
      padding: 32px 16px;
      box-sizing: border-box;
    }
    .app-card {
      width: 100%;
      max-width: 440px;
      background-color: #ffffff;
      border-radius: 28px;
      padding: 24px;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.08);
      border: 1px solid #e2e8f0;
      gap: 16px;
    }
    .top-bar {
      flex-direction: row;
      justify-content: flex-end;
      gap: 8px;
    }
    .action-btn {
      width: 40px;
      height: 40px;
      border-radius: 20px;
      background-color: #f1f5f9;
      justify-content: center;
      align-items: center;
    }
    .action-btn-icon {
      font-size: 18px;
    }
    .header-section {
      align-items: center;
      gap: 6px;
      margin-bottom: 8px;
    }
    .logo-wrapper {
      padding: 10px;
      border-radius: 20px;
      background-color: #f8fafc;
      border: 1px solid #f1f5f9;
      margin-bottom: 6px;
    }
    .logo-img {
      width: 64px;
      height: 64px;
      object-fit: contain;
    }
    .app-title {
      font-size: 22px;
      font-weight: 800;
      color: #002E62;
      text-align: center;
    }
    .app-subtitle {
      font-size: 13px;
      color: #64748b;
      text-align: center;
      max-width: 280px;
      line-height: 18px;
    }
    .loading-overlay {
      position: fixed;
      inset: 0;
      background-color: rgba(0, 0, 0, 0.6);
      justify-content: center;
      align-items: center;
      z-index: 50;
    }
    .loading-card {
      padding: 24px 32px;
      background-color: #ffffff;
      border-radius: 18px;
      box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.2);
    }
    .loading-text {
      font-size: 15px;
      font-weight: 700;
      color: #002E62;
    }
    .toast-banner {
      position: fixed;
      bottom: 24px;
      left: 20px;
      right: 20px;
      max-width: 400px;
      margin-horizontal: auto;
      background-color: #065f46;
      border-radius: 16px;
      padding: 14px 18px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      z-index: 60;
      box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.2);
    }
    .toast-error {
      background-color: #991b1b;
    }
    .toast-content {
      flex: 1;
      gap: 2px;
    }
    .toast-title {
      color: #ffffff;
      font-size: 13px;
      font-weight: 700;
    }
    .toast-message {
      color: rgba(255, 255, 255, 0.9);
      font-size: 12px;
    }
    .toast-close {
      padding: 6px;
    }
    .toast-close-text {
      color: #ffffff;
      font-size: 14px;
    }
    @media (prefers-color-scheme: dark) {
      .app-card {
        background-color: #1e293b;
        border-color: #334155;
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5);
      }
      .action-btn {
        background-color: #334155;
      }
      .logo-wrapper {
        background-color: #0f172a;
        border-color: #1e293b;
      }
      .app-title {
        color: #38bdf8;
      }
      .app-subtitle {
        color: #94a3b8;
      }
      .loading-card {
        background-color: #1e293b;
      }
      .loading-text {
        color: #38bdf8;
      }
    }
  `
})
export class App implements OnInit {
  isDark = signal(false);
  isScanning = signal(false);
  isLoading = signal(false);
  scannedValue = signal('');
  notification = signal<NotificationState | null>(null);

  private storageService = inject(StorageService);
  private notifTimer: any = null;

  constructor() {}

  ngOnInit(): void {
    const saved = this.storageService.getThemeMode();
    if (saved === 'dark') {
      this.isDark.set(true);
    } else if (saved === 'light') {
      this.isDark.set(false);
    } else {
      this.isDark.set(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches);
    }
  }

  toggleTheme(): void {
    const next = !this.isDark();
    this.isDark.set(next);
    this.storageService.saveThemeMode(next ? 'dark' : 'light');
  }

  onQrScanned(code: string): void {
    this.scannedValue.set(code);
    this.isScanning.set(false);
    this.showNotification({
      type: 'success',
      title: 'QR Code Scanned',
      message: 'Parameters loaded from QR.',
    });
  }

  showNotification(notify: NotificationState): void {
    this.notification.set(notify);
    if (this.notifTimer) {
      clearTimeout(this.notifTimer);
    }
    this.notifTimer = setTimeout(() => {
      this.notification.set(null);
    }, 6000);
  }
}
