// App.tsx
import React, { useEffect, useRef, useState } from "react";
import {
  StyleSheet,
  Text,
  View,
  SafeAreaView,
  Image,
  useWindowDimensions,
  ScrollView,
  Platform,
  ActivityIndicator,
  useColorScheme,
} from "react-native";
import { PaperProvider, IconButton } from "react-native-paper";
import { StatusBar } from "expo-status-bar";

import { QrCodeScan } from "./src/components/QrCodeScan";
import ReportForm, { ReportFormHandle } from "./src/components/ReportForm";
import { AppIcon } from "./src/components/AppIcon";
import ErrorBoundary from "./src/components/ErrorBoundary";
import { lightTheme, darkTheme } from "./src/theme";
import { storageService } from "./src/services/StorageService";
import logoImg from "./src/assets/images/logo-mini.png";

export { lightTheme, darkTheme };
export const theme = lightTheme;

interface NotificationState {
  type: "success" | "error";
  title: string;
  message: string;
}

export default function App() {
  const systemColorScheme = useColorScheme();
  const [themePreference, setThemePreference] = useState<
    "light" | "dark" | "system"
  >("system");
  const [loading, setLoading] = useState(false);
  const [qrScan, setQrScan] = useState(false);
  const [qrScanValue, setQrScanValue] = useState("");
  const [isCancel, setIsCancel] = useState(false);
  const [notification, setNotification] = useState<NotificationState | null>(
    null,
  );

  const reportFormRef = useRef<ReportFormHandle | null>(null);
  const { width, height } = useWindowDimensions();
  const isLandscapeMode = width > height && width > 600;

  // Load saved theme preference
  useEffect(() => {
    async function loadTheme() {
      const saved = await storageService.getThemeMode();
      if (saved) {
        setThemePreference(saved);
      }
    }
    loadTheme();
  }, []);

  const isDarkMode =
    themePreference === "dark" ||
    (themePreference === "system" && systemColorScheme === "dark");

  const currentTheme = isDarkMode ? darkTheme : lightTheme;

  const toggleTheme = async () => {
    const nextMode = isDarkMode ? "light" : "dark";
    setThemePreference(nextMode);
    await storageService.saveThemeMode(nextMode);
  };

  const showNotification = (
    type: "success" | "error",
    title: string,
    message: string,
  ) => {
    setNotification({ type, title, message });
    setTimeout(() => {
      setNotification((curr) => (curr?.title === title ? null : curr));
    }, 6000);
  };

  return (
    <ErrorBoundary fallbackTitle="Error en la aplicación">
      <PaperProvider
        theme={currentTheme}
        {...(Platform.OS === "web"
          ? {
              settings: {
                icon: (props: any) => <AppIcon {...props} />,
              },
            }
          : {})}
      >
        <SafeAreaView
          style={[
            styles.safeArea,
            {
              backgroundColor: qrScan
                ? "#000000"
                : currentTheme.colors.background,
            },
          ]}
        >
          <StatusBar
            style={qrScan ? "light" : isDarkMode ? "light" : "dark"}
            backgroundColor={
              qrScan ? "#000000" : currentTheme.colors.background
            }
          />

          {!qrScan ? (
            <ScrollView
              contentContainerStyle={styles.scrollContent}
              keyboardShouldPersistTaps="handled"
              showsVerticalScrollIndicator={false}
            >
              <View style={styles.container}>
                {/* Card wrapper */}
                <View
                  style={[
                    styles.card,
                    {
                      backgroundColor: currentTheme.custom.cardBackground,
                      borderColor: currentTheme.custom.cardBorder,
                    },
                  ]}
                >
                  {/* Top Bar with Theme toggle & QR scan button */}
                  <View style={styles.topBar}>
                    <View style={styles.topBarActions}>
                      {/* Theme toggle button */}
                      <IconButton
                        icon={
                          isDarkMode ? "white-balance-sunny" : "weather-night"
                        }
                        iconColor={isDarkMode ? "#38bdf8" : "#002E62"}
                        size={22}
                        mode="contained-tonal"
                        containerColor={currentTheme.custom.qrButtonBg}
                        onPress={toggleTheme}
                        accessibilityLabel="Cambiar tema claro u oscuro"
                        style={styles.actionBtn}
                      />

                      {/* QR scan trigger button */}
                      <IconButton
                        icon="qrcode-scan"
                        iconColor={isDarkMode ? "#38bdf8" : "#002E62"}
                        size={22}
                        mode="contained-tonal"
                        containerColor={currentTheme.custom.qrButtonBg}
                        onPress={() => setQrScan(true)}
                        accessibilityLabel="Escanear código QR"
                        style={styles.actionBtn}
                      />
                    </View>
                  </View>

                  {/* Header branding */}
                  <View style={styles.header}>
                    <View
                      style={[
                        styles.logoContainer,
                        isDarkMode && styles.logoContainerDark,
                      ]}
                    >
                      <Image
                        source={
                          typeof logoImg === "string"
                            ? { uri: logoImg }
                            : logoImg
                        }
                        style={styles.logo}
                        resizeMode="contain"
                      />
                    </View>

                    <Text
                      style={[
                        styles.subtitle,
                        { color: currentTheme.custom.mutedText },
                      ]}
                    >
                      Enter or scan your report key to download your PGx report
                    </Text>
                  </View>

                  {/* Form Component */}
                  <View style={styles.formContainer}>
                    <ReportForm
                      ref={reportFormRef}
                      loading={setLoading}
                      scanValue={qrScanValue}
                      cancel={isCancel}
                      qrScanValue={setQrScanValue}
                      onNotification={showNotification}
                    />
                  </View>
                </View>
              </View>
            </ScrollView>
          ) : (
            <QrCodeScan
              onClear={setQrScan}
              qrScanValue={(val) => {
                setQrScanValue(val);
                setQrScan(false);
                showNotification(
                  "success",
                  "QR Code Scanned",
                  "Parameters loaded from QR.",
                );
              }}
              isLandscape={isLandscapeMode}
            />
          )}

          {/* Global Loading Overlay */}
          {loading && (
            <View style={styles.loadingOverlay}>
              <View
                style={[
                  styles.loadingCard,
                  {
                    backgroundColor: currentTheme.custom.cardBackground,
                    borderColor: currentTheme.custom.cardBorder,
                  },
                ]}
              >
                <ActivityIndicator
                  size="large"
                  color={currentTheme.colors.primary}
                />
                <Text
                  style={[
                    styles.loadingCardText,
                    { color: currentTheme.colors.onSurface },
                  ]}
                >
                  Loading PGx Report...
                </Text>
              </View>
            </View>
          )}

          {/* Toast / Notification Banner */}
          {notification && (
            <View
              style={[
                styles.toastBanner,
                notification.type === "error"
                  ? styles.toastError
                  : styles.toastSuccess,
                {
                  backgroundColor:
                    notification.type === "error"
                      ? isDarkMode
                        ? "#450a0a"
                        : "#fef2f2"
                      : isDarkMode
                        ? "#052e16"
                        : "#f0fdf4",
                  borderColor:
                    notification.type === "error"
                      ? isDarkMode
                        ? "#991b1b"
                        : "#fca5a5"
                      : isDarkMode
                        ? "#166534"
                        : "#86efac",
                },
              ]}
            >
              <View style={styles.toastTextContainer}>
                <Text
                  style={[
                    styles.toastTitle,
                    { color: currentTheme.colors.onSurface },
                  ]}
                >
                  {notification.title}
                </Text>
                <Text
                  style={[
                    styles.toastMessage,
                    { color: currentTheme.custom.mutedText },
                  ]}
                >
                  {notification.message}
                </Text>
              </View>
              <IconButton
                icon="close"
                size={18}
                iconColor={currentTheme.custom.mutedText}
                onPress={() => setNotification(null)}
                style={styles.toastClose}
              />
            </View>
          )}
        </SafeAreaView>
      </PaperProvider>
    </ErrorBoundary>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingVertical: 24,
    paddingHorizontal: 16,
  },
  container: {
    width: "100%",
    maxWidth: 500,
    alignSelf: "center",
  },
  card: {
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    shadowColor: "#002E62",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 4,
  },
  topBarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionBtn: {
    margin: 0,
  },
  header: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 16,
  },
  logoContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    borderRadius: 20,
    overflow: "hidden",
  },
  logoContainerDark: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  logo: {
    width: 240,
    height: 105,
    borderRadius: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 14,
    textAlign: "center",
    marginTop: 4,
    maxWidth: 320,
    lineHeight: 20,
  },
  formContainer: {
    marginTop: 8,
  },
  footerNote: {
    marginTop: 18,
    alignItems: "center",
  },
  footerText: {
    fontSize: 11,
    textAlign: "center",
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
  loadingCard: {
    padding: 24,
    borderRadius: 16,
    alignItems: "center",
    gap: 12,
    minWidth: 200,
    borderWidth: 1,
    elevation: 8,
  },
  loadingCardText: {
    fontSize: 14,
    fontWeight: "600",
    marginTop: 8,
  },
  toastBanner: {
    position: "absolute",
    bottom: 24,
    left: 20,
    right: 20,
    maxWidth: 420,
    alignSelf: "center",
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    zIndex: 1000,
    elevation: 6,
  },
  toastSuccess: {},
  toastError: {},
  toastTextContainer: {
    flex: 1,
    paddingRight: 8,
  },
  toastTitle: {
    fontSize: 13,
    fontWeight: "bold",
  },
  toastMessage: {
    fontSize: 12,
    marginTop: 2,
  },
  toastClose: {
    margin: 0,
  },
});

// src/app/app.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { View, Text, Pressable, ScrollView, Image } from '@ng-native/components';
import { StorageService } from './services/storage.service';
import { ReportFormComponent } from './components/report-form.component';
import { QrScannerComponent } from './components/qr-scanner.component';
import { NotificationState } from './models/report.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ScrollView, View, Text, Pressable, Image, ReportFormComponent, QrScannerComponent],
  template: `
    <view class="screen-root" [class.dark-theme]="isDark()">
      <!-- Scrollable Main Content -->
      <scroll-view class="scroll-container">
        <view class="content-wrapper">
          <view class="app-card">
            <!-- Top Bar with Theme and QR buttons -->
            <view class="top-bar">
              <pressable class="action-btn" (press)="toggleTheme()">
                <text class="action-btn-icon">{{ isDark() ? '☀️' : '🌙' }}</text>
              </pressable>

              <pressable class="action-btn" (press)="isScanning.set(true)">
                <text class="action-btn-icon">📷</text>
              </pressable>
            </view>

            <!-- Header Branding -->
            <view class="header-section">
              <view class="logo-wrapper">
                <image source="/src/assets/images/logo-mini.png" class="logo-img" />
              </view>
              <text class="app-title">PGx Reports</text>
              <text class="app-subtitle">
                Enter or scan your report key to download your PGx report
              </text>
            </view>

            <!-- Form Component -->
            <app-report-form
              [scanValue]="scannedValue()"
              (loadingState)="isLoading.set($event)"
              (notify)="showNotification($event)"
            />
          </view>
        </view>
      </scroll-view>

      <!-- Live QR Scanner View -->
      <app-qr-scanner
        *ngIf="isScanning()"
        (qrDetected)="onQrScanned($event)"
        (closeScanner)="isScanning.set(false)"
      />

      <!-- Global Loading Overlay -->
      <view *ngIf="isLoading()" class="loading-overlay">
        <view class="loading-card">
          <text class="loading-text">Loading PGx Report...</text>
        </view>
      </view>

      <!-- Toast / Notification Banner -->
      <view *ngIf="notification()" class="toast-banner" [class.toast-error]="notification()?.type === 'error'">
        <view class="toast-content">
          <text class="toast-title">{{ notification()?.title }}</text>
          <text class="toast-message">{{ notification()?.message }}</text>
        </view>
        <pressable class="toast-close" (press)="notification.set(null)">
          <text class="toast-close-text">✕</text>
        </pressable>
      </view>
    </view>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      flex: 1 1 auto;
      width: 100%;
      min-height: 100vh;
    }
    .screen-root {
      display: flex;
      flex-direction: column;
      flex: 1 1 auto;
      width: 100%;
      min-height: 100vh;
      background-color: #f8fafc;
    }
    .dark-theme {
      background-color: #0b1329;
    }
    .scroll-container {
      display: flex;
      flex-direction: column;
      flex: 1 1 auto;
      width: 100%;
      min-height: 100vh;
    }
    .content-wrapper {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 100%;
      min-height: 100vh;
      padding: 32px 16px;
      box-sizing: border-box;
    }
    .app-card {
      width: 100%;
      max-width: 440px;
      background-color: #ffffff;
      border-radius: 28px;
      padding: 24px;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.08);
      border: 1px solid #e2e8f0;
      gap: 16px;
    }
    .top-bar {
      flex-direction: row;
      justify-content: flex-end;
      gap: 8px;
    }
    .action-btn {
      width: 40px;
      height: 40px;
      border-radius: 20px;
      background-color: #f1f5f9;
      justify-content: center;
      align-items: center;
    }
    .action-btn-icon {
      font-size: 18px;
    }
    .header-section {
      align-items: center;
      gap: 6px;
      margin-bottom: 8px;
    }
    .logo-wrapper {
      padding: 10px;
      border-radius: 20px;
      background-color: #f8fafc;
      border: 1px solid #f1f5f9;
      margin-bottom: 6px;
    }
    .logo-img {
      width: 64px;
      height: 64px;
      object-fit: contain;
    }
    .app-title {
      font-size: 22px;
      font-weight: 800;
      color: #002E62;
      text-align: center;
    }
    .app-subtitle {
      font-size: 13px;
      color: #64748b;
      text-align: center;
      max-width: 280px;
      line-height: 18px;
    }
    .loading-overlay {
      position: fixed;
      inset: 0;
      background-color: rgba(0, 0, 0, 0.6);
      justify-content: center;
      align-items: center;
      z-index: 50;
    }
    .loading-card {
      padding: 24px 32px;
      background-color: #ffffff;
      border-radius: 18px;
      box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.2);
    }
    .loading-text {
      font-size: 15px;
      font-weight: 700;
      color: #002E62;
    }
    .toast-banner {
      position: fixed;
      bottom: 24px;
      left: 20px;
      right: 20px;
      max-width: 400px;
      margin-horizontal: auto;
      background-color: #065f46;
      border-radius: 16px;
      padding: 14px 18px;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      z-index: 60;
      box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.2);
    }
    .toast-error {
      background-color: #991b1b;
    }
    .toast-content {
      flex: 1;
      gap: 2px;
    }
    .toast-title {
      color: #ffffff;
      font-size: 13px;
      font-weight: 700;
    }
    .toast-message {
      color: rgba(255, 255, 255, 0.9);
      font-size: 12px;
    }
    .toast-close {
      padding: 6px;
    }
    .toast-close-text {
      color: #ffffff;
      font-size: 14px;
    }
    @media (prefers-color-scheme: dark) {
      .app-card {
        background-color: #1e293b;
        border-color: #334155;
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5);
      }
      .action-btn {
        background-color: #334155;
      }
      .logo-wrapper {
        background-color: #0f172a;
        border-color: #1e293b;
      }
      .app-title {
        color: #38bdf8;
      }
      .app-subtitle {
        color: #94a3b8;
      }
      .loading-card {
        background-color: #1e293b;
      }
      .loading-text {
        color: #38bdf8;
      }
    }
  `
})
export class App implements OnInit {
  isDark = signal(false);
  isScanning = signal(false);
  isLoading = signal(false);
  scannedValue = signal('');
  notification = signal<NotificationState | null>(null);

  private storageService = inject(StorageService);
  private notifTimer: any = null;

  constructor() {}

  ngOnInit(): void {
    const saved = this.storageService.getThemeMode();
    if (saved === 'dark') {
      this.isDark.set(true);
    } else if (saved === 'light') {
      this.isDark.set(false);
    } else {
      this.isDark.set(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches);
    }
  }

  toggleTheme(): void {
    const next = !this.isDark();
    this.isDark.set(next);
    this.storageService.saveThemeMode(next ? 'dark' : 'light');
  }

  onQrScanned(code: string): void {
    this.scannedValue.set(code);
    this.isScanning.set(false);
    this.showNotification({
      type: 'success',
      title: 'QR Code Scanned',
      message: 'Parameters loaded from QR.',
    });
  }

  showNotification(notify: NotificationState): void {
    this.notification.set(notify);
    if (this.notifTimer) {
      clearTimeout(this.notifTimer);
    }
    this.notifTimer = setTimeout(() => {
      this.notification.set(null);
    }, 6000);
  }
}
